version: "2"

linters:
  default: all

  settings:
    cyclop:
      max-complexity: 15

    funlen:
      lines: 100
      statements: 50
      ignore-comments: true

    nestif:
      min-complexity: 4

    gocyclo:
      min-complexity: 15

    gocognit:
      min-complexity: 20

    errcheck:
      check-type-assertions: true
      check-blank: false
      exclude-functions:
        - io.Copy
        - io.Copy(*bytes.Buffer)
        - io.CopyBuffer
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
        - (net/http.ResponseWriter).Write
        - (*encoding/json.Encoder).Encode
        - (*encoding/xml.Encoder).Encode
        - (hash.Hash).Write
        - crypto/rand.Read
        - encoding/binary.Read
        - encoding/binary.Write

    govet:
      enable-all: true
      disable:
        - shadow  # Too strict, common variable shadowing is often intentional

    revive:
      rules:
        - name: exported
          arguments:
            - "checkPrivateReceivers"
            - "sayRepetitiveInsteadOfStutters"
        - name: var-naming
        - name: package-comments
        - name: error-return
        - name: error-naming
        - name: error-strings
        - name: receiver-naming
        - name: indent-error-flow
        - name: if-return

    staticcheck:
      checks:
        - all
        - "-SA9003"  # Empty branch - often intentional for TODO stubs
        - "-SA1012"  # nil context - sometimes intentional in tests
        - "-SA1026"  # xml.Encode map - false positive when used for error responses
        - "-ST1005"  # Error strings should not be capitalized - too strict for API errors
        - "-ST1003"  # Initialisms (ACL vs Acl) - S3 API compatibility
        - "-ST1000"  # Package comments - not required for internal packages
        - "-ST1020"  # Comment format on methods - style preference
        - "-ST1021"  # Comment format on types - style preference
        - "-ST1022"  # Comment format on consts - style preference
        - "-S1008"   # Simplify return - readability preference
        - "-QF1002"  # Tagged switch - style preference
        - "-QF1003"  # Tagged switch - style preference

    gosec:
      excludes:
        - G101  # Look for hard coded credentials - false positives with test constants
        - G104  # Audit errors not checked - covered by errcheck
        - G204  # Subprocess launched with variable - required for CLI commands
      config:
        G306: "0644"  # File permissions

    errorlint:
      errorf: true
      asserts: true
      comparison: true

  enable:
    # Security & Bug Detection (High Priority)
    - gosec          # Security issues
    - govet          # Go vet
    - staticcheck    # Comprehensive static analysis

    # Common Mistakes
    - ineffassign    # Ineffectual assignments
    - unused         # Unused code

    # Code Quality & Complexity
    - gocyclo        # Cyclomatic complexity
    - gocognit       # Cognitive complexity
    - nestif         # Deep nesting
    - funlen         # Function length

    # Best Practices
    - errorlint      # Error handling
    - gocritic       # Meta-linter with many checks
    - revive         # Fast linter (replaces golint)

    # Concurrency
    - contextcheck   # Context usage

    # Style
    - misspell       # Spelling
    - whitespace     # Whitespace issues

    # Documentation
    - godot          # Comment periods

  disable:
    # Disabled for now - enable incrementally
    - gochecknoglobals  # Too strict - globals needed for config
    - gochecknoinits    # Too strict - init() used in registration
    - wrapcheck         # Too strict - error wrapping is situational
    - exhaustive        # Too strict - not all cases need handling
    - exhaustruct       # Too strict - partial struct init is common
    - nlreturn          # Style preference
    - wsl               # Style preference
    - lll               # Line length - not enforced
    - forbidigo         # Bans specific identifiers - not needed
    - varnamelen        # Variable name length - too strict
    - tagliatelle       # Tag format - JSON compatibility
    - paralleltest      # Test parallelization - not always desired
    - tparallel         # Test parallelization - not always desired
    - testpackage       # Test package naming - internal tests needed
    - godox             # TODO comments - tracked separately in issues
    - depguard          # Dependency restrictions - not configured for this project
    - err113            # Dynamic errors - static errors add unnecessary boilerplate for internal errors
    - dogsled           # Blank identifiers - sometimes necessary for ignored return values
    - embeddedstructfieldcheck # Embedded field ordering - style preference
    - errchkjson        # JSON marshal error checking - interface{} marshaling is safe
    - errcheck          # Unchecked errors - too many false positives for cleanup operations
    - errorlint         # Error comparison - errors.Is() not always appropriate for internal errors
    - errname           # Error naming convention - project uses ErrXxx style consistently
    - funcorder         # Function ordering - style preference, not enforced
    - forcetypeassert   # Type assertion checking - sometimes appropriate for known types

  exclusions:
    paths:
      - vendor
      - node_modules
      - web
      - ".*\\.pb\\.go$"
      - ".*generated.*\\.go$"

    rules:
      # Exclude test files from certain checks
      - path: _test\.go
        linters:
          - funlen      # Test functions can be long
          - gocyclo     # Test complexity is acceptable
          - gocognit    # Test complexity is acceptable
          - errcheck    # Tests often intentionally ignore errors
          - gosec       # Tests may use insecure operations

      # Exclude benchmark files
      - path: _bench_test\.go
        linters:
          - funlen
          - gocyclo
          - gocognit
          - errcheck

      # Exclude integration test files
      - path: internal/integration/
        linters:
          - funlen
          - gocyclo
          - gosec

      # Exclude generated or stub code
      - path: internal/transport/rdma/
        linters:
          - unused      # RDMA transport has placeholder fields
          - gocritic    # Stub implementations

      - path: internal/dpu/
        linters:
          - unused      # DPU code has placeholder fields
          - gocritic

      - path: internal/backup/pitr\.go
        linters:
          - unused      # Progress tracking fields for future use

      # Exclude specific paths from unused checks (reserved for future)
      - path: internal/cache/dram/
        linters:
          - unused

      - path: internal/catalog/
        linters:
          - unused

      - path: internal/cluster/membership\.go
        linters:
          - unused

      - path: internal/mcp/
        linters:
          - unused

      - path: internal/metadata/raft\.go
        linters:
          - unused

      - path: internal/nim/
        linters:
          - unused

      - path: internal/object/service\.go
        linters:
          - unused

      # Allow certain patterns in specific files
      - path: internal/server/server\.go
        text: "cyclomatic complexity"
        linters:
          - gocyclo
          - gocognit
          - cyclop

      - path: internal/api/s3/
        text: "cyclomatic complexity"
        linters:
          - gocyclo      # S3 API handlers have complex routing
          - cyclop

      # Complex routing and business logic in API handlers
      - path: internal/api/(admin|console)/
        text: "cyclomatic complexity"
        linters:
          - cyclop

      - path: internal/api/middleware/
        text: "cyclomatic complexity"
        linters:
          - cyclop

      # Complex business logic requiring extensive conditional checks
      - path: internal/(analytics|audit|auth|dlp|iam|lifecycle|policy|replication|tiering)/
        text: "cyclomatic complexity"
        linters:
          - cyclop

      # Storage and transport layer with complex device/protocol handling
      - path: internal/(storage|transport)/
        text: "cyclomatic complexity"
        linters:
          - cyclop

      # Format parsing and evaluation (Parquet, etc.)
      - path: internal/select/
        text: "cyclomatic complexity"
        linters:
          - cyclop

      # Security operations with multiple validation steps
      - path: internal/security/
        text: "cyclomatic complexity"
        linters:
          - cyclop

      # Complex test scenarios
      - path: internal/.*/.*_test\.go
        text: "cyclomatic complexity"
        linters:
          - cyclop

      # CLI commands with multiple options
      - path: cmd/nebulaio-cli/
        text: "cyclomatic complexity"
        linters:
          - cyclop

      # Express One Zone has complex object listing logic
      - path: internal/express/
        text: "cyclomatic complexity"
        linters:
          - cyclop

      # KMS providers have complex initialization sequences
      - path: internal/kms/
        text: "cyclomatic complexity"
        linters:
          - cyclop

      # Cluster management with complex state handling
      - path: internal/cluster/
        text: "cyclomatic complexity"
        linters:
          - cyclop

      # Additional paths with complex business logic
      - path: internal/(backup|catalog|config|firewall|hardware|iceberg|lambda|migration|object|s3select|tenant)/
        text: "cyclomatic complexity"
        linters:
          - cyclop

      # Metadata store with complex FSM processing
      - path: internal/metadata/
        text: "cyclomatic complexity"
        linters:
          - cyclop

      # Allow InsecureSkipVerify in test helpers
      - path: internal/.*test.*\.go
        text: "G402.*InsecureSkipVerify"
        linters:
          - gosec

      # Allow weak random in non-cryptographic contexts
      - path: internal/.*
        text: "G404.*weak random"
        linters:
          - gosec

      # Context in struct is acceptable for lifecycle management in background workers
      # These structs use context.WithCancel for coordinating goroutine shutdown
      - path: internal/audit/(enhanced|logger)\.go
        text: "found a struct that contains a context.Context field"
        linters:
          - containedctx

      # Test suites and background workers legitimately store context for lifecycle management
      - path: internal/(integration|backup|cluster|events|migration|replication|cache|dpu|storage)/.*\.go
        text: "found a struct that contains a context.Context field"
        linters:
          - containedctx

      # Shutdown contexts should be independent from parent context with own timeout
      - path: internal/server/server\.go
        text: "Non-inherited new context"
        linters:
          - contextcheck

      # Multipart copy operations may need independent contexts for sub-operations
      - path: internal/s3/multipart_copy\.go
        text: "(Non-inherited new context|cyclomatic complexity)"
        linters:
          - contextcheck
          - cyclop

      # Discovery and metadata methods are synchronous and don't need context
      - path: internal/api/admin/(cluster|handler)\.go
        text: "Function .* should pass the context parameter"
        linters:
          - contextcheck

      - path: internal/metadata/dragonboat_store\.go
        text: "Function .* should pass the context parameter"
        linters:
          - contextcheck

      # Replication filter methods are pure functions
      - path: internal/replication/cross_region\.go
        text: "Function `matchesFilter` should pass the context parameter"
        linters:
          - contextcheck

      # Tiering storage lookups are synchronous
      - path: internal/tiering/.*\.go
        text: "Function `GetByTier` should pass the context parameter"
        linters:
          - contextcheck

      # Test helper methods
      - path: internal/tiering/tiering_test\.go
        text: "should pass the context parameter"
        linters:
          - contextcheck

      # Express One Zone - ignore specific error checks for response writing
      - path: internal/express/express\.go
        text: "Error return value.*is not checked"
        linters:
          - errcheck

      # Key rotation - ignore error checks for cleanup operations
      - path: internal/encryption/key_rotation\.go
        text: "Error return value.*is not checked"
        linters:
          - errcheck

      # MCP server - ignore error checks for cleanup operations
      - path: internal/mcp/server\.go
        text: "Error return value.*is not checked"
        linters:
          - errcheck

      # Security operations - type assertions and CRL creation
      - path: internal/security/mtls\.go
        text: "Error return value.*is not checked"
        linters:
          - errcheck

      # Direct I/O storage - low-level operations
      - path: internal/storage/volume/directio\.go
        text: "Error return value.*is not checked"
        linters:
          - errcheck

run:
  go: '1.24'
  timeout: 5m
  tests: true
  build-tags:
    - integration
  relative-path-mode: 'gomod'

issues:
  uniq-by-line: false
