version: "2"

linters:
  default: none
  enable:
    # Adding linters back to find the failing one
    - unused          # Unused code detection
    - staticcheck     # Static analysis

  settings:
    staticcheck:
      checks:
        - all
        - "-SA9003"
        - "-SA1012"
        - "-SA1026"
        - "-ST1005"
        - "-ST1003"
        - "-ST1000"
        - "-ST1020"
        - "-ST1021"
        - "-ST1022"
        - "-S1008"
        - "-QF1002"
        - "-QF1003"

  exclusions:
    paths:
      - vendor
      - node_modules
      - web
      - ".*\\.pb\\.go$"
      - ".*generated.*\\.go$"

    rules:
      - path: _test\.go
        linters:
          - errcheck

      - path: internal/transport/rdma/
        linters:
          - unused

      - path: internal/dpu/
        linters:
          - unused

      - path: internal/backup/pitr\.go
        linters:
          - unused

      - path: internal/cache/dram/
        linters:
          - unused

      - path: internal/catalog/
        linters:
          - unused

      - path: internal/cluster/membership\.go
        linters:
          - unused

      - path: internal/mcp/
        linters:
          - unused

      - path: internal/metadata/raft\.go
        linters:
          - unused

      - path: internal/nim/
        linters:
          - unused

      - path: internal/object/service\.go
        linters:
          - unused

run:
  go: '1.24'
  timeout: 5m
  tests: true
  build-tags:
    - integration
  relative-path-mode: 'gomod'

issues:
  uniq-by-line: false
